
public class Catch {

	public static void main(String[] args) {
		
		try {
			int[] a = {4, 5, 1};
			System.out.println(a[0]);	
		} catch(Exception e) {
			System.out.println("An exception happened");
		}

	}

}
